// Code generated by goctl. DO NOT EDIT!
// Source: collection.proto

package catrpc

import (
	"context"
	pb2 "github.com/xh-polaris/meowchat-collection-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCatReq      = pb2.AddCatReq
	AddCatResp     = pb2.AddCatResp
	Cat            = pb2.Cat
	DeleteCatReq   = pb2.DeleteCatReq
	DeleteCatResp  = pb2.DeleteCatResp
	GetCatReq      = pb2.GetCatReq
	GetCatResp     = pb2.GetCatResp
	GetManyCatReq  = pb2.GetManyCatReq
	GetManyCatResp = pb2.GetManyCatResp
	UpdateCatReq   = pb2.UpdateCatReq
	UpdateCatResp  = pb2.UpdateCatResp

	CatRpc interface {
		GetManyCat(ctx context.Context, in *GetManyCatReq, opts ...grpc.CallOption) (*GetManyCatResp, error)
		GetCat(ctx context.Context, in *GetCatReq, opts ...grpc.CallOption) (*GetCatResp, error)
		AddCat(ctx context.Context, in *AddCatReq, opts ...grpc.CallOption) (*AddCatResp, error)
		UpdateCat(ctx context.Context, in *UpdateCatReq, opts ...grpc.CallOption) (*UpdateCatResp, error)
		DeleteCat(ctx context.Context, in *DeleteCatReq, opts ...grpc.CallOption) (*DeleteCatResp, error)
	}

	defaultCatRpc struct {
		cli zrpc.Client
	}
)

func NewCatRpc(cli zrpc.Client) CatRpc {
	return &defaultCatRpc{
		cli: cli,
	}
}

func (m *defaultCatRpc) GetManyCat(ctx context.Context, in *GetManyCatReq, opts ...grpc.CallOption) (*GetManyCatResp, error) {
	client := pb2.NewCatRpcClient(m.cli.Conn())
	return client.GetManyCat(ctx, in, opts...)
}

func (m *defaultCatRpc) GetCat(ctx context.Context, in *GetCatReq, opts ...grpc.CallOption) (*GetCatResp, error) {
	client := pb2.NewCatRpcClient(m.cli.Conn())
	return client.GetCat(ctx, in, opts...)
}

func (m *defaultCatRpc) AddCat(ctx context.Context, in *AddCatReq, opts ...grpc.CallOption) (*AddCatResp, error) {
	client := pb2.NewCatRpcClient(m.cli.Conn())
	return client.AddCat(ctx, in, opts...)
}

func (m *defaultCatRpc) UpdateCat(ctx context.Context, in *UpdateCatReq, opts ...grpc.CallOption) (*UpdateCatResp, error) {
	client := pb2.NewCatRpcClient(m.cli.Conn())
	return client.UpdateCat(ctx, in, opts...)
}

func (m *defaultCatRpc) DeleteCat(ctx context.Context, in *DeleteCatReq, opts ...grpc.CallOption) (*DeleteCatResp, error) {
	client := pb2.NewCatRpcClient(m.cli.Conn())
	return client.DeleteCat(ctx, in, opts...)
}
