// Code generated by goctl. DO NOT EDIT!
// Source: collection.proto

package server

import (
	"context"

	"github.com/xh-polaris/meowchat-collection-rpc/internal/logic"
	"github.com/xh-polaris/meowchat-collection-rpc/internal/svc"
	"github.com/xh-polaris/meowchat-collection-rpc/pb"
)

type CatRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCatRpcServer
}

func NewCatRpcServer(svcCtx *svc.ServiceContext) *CatRpcServer {
	return &CatRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *CatRpcServer) GetManyCat(ctx context.Context, in *pb.GetManyCatReq) (*pb.GetManyCatResp, error) {
	l := logic.NewGetManyCatLogic(ctx, s.svcCtx)
	return l.GetManyCat(in)
}

func (s *CatRpcServer) GetCat(ctx context.Context, in *pb.GetCatReq) (*pb.GetCatResp, error) {
	l := logic.NewGetCatLogic(ctx, s.svcCtx)
	return l.GetCat(in)
}

func (s *CatRpcServer) AddCat(ctx context.Context, in *pb.AddCatReq) (*pb.AddCatResp, error) {
	l := logic.NewAddCatLogic(ctx, s.svcCtx)
	return l.AddCat(in)
}

func (s *CatRpcServer) UpdateCat(ctx context.Context, in *pb.UpdateCatReq) (*pb.UpdateCatResp, error) {
	l := logic.NewUpdateCatLogic(ctx, s.svcCtx)
	return l.UpdateCat(in)
}

func (s *CatRpcServer) DeleteCat(ctx context.Context, in *pb.DeleteCatReq) (*pb.DeleteCatResp, error) {
	l := logic.NewDeleteCatLogic(ctx, s.svcCtx)
	return l.DeleteCat(in)
}
